/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "article": string|undefined
  "article__description": string|undefined
  "article__goals": string|undefined
  "article__goals--flow": string|undefined
  "article__stack": string|undefined
  "article__title": string|undefined
  "article__title--range": string|undefined
  "cv": string|undefined
  "cv__competences": string|undefined
  "cv__description": string|undefined
  "cv__education": string|undefined
  "cv__experience": string|undefined
  "cv__languages": string|undefined
  "cv__links": string|undefined
  "cv__objectives": string|undefined
  "cv__projects": string|undefined
  "cv__title": string|undefined
  "link": string|undefined
  "link--email": string|undefined
  "link--github": string|undefined
  "link--html": string|undefined
  "link--linkedin": string|undefined
  "link--location": string|undefined
  "link--npm": string|undefined
  "link--pdf": string|undefined
  "link--phone": string|undefined
  "link--skype": string|undefined
  "links_group": string|undefined
  "links_group--contacts": string|undefined
  "links_group--etc": string|undefined
  "links_group--social": string|undefined
  "location": string|undefined
  "location__city": string|undefined
  "location__description": string|undefined
  "location__title": string|undefined
  "section__title": string|undefined
}
